(function(){
  "use strict";
  const LI=window.LI=window.LI||{};
  function run(){
    const results=[];const test=(name,fn)=>{try{const detail=fn();results.push({name,ok:true,detail:detail??"OK"});}catch(error){results.push({name,ok:false,detail:error.message});}};const assert=(v,m)=>{if(!v)throw new Error(m);};
    test("全レシピ参照",()=>{for(const r of LI.DATA.recipes){assert(LI.DATA.items[r.output],`出力 ${r.output}`);for(const k of Object.keys(r.cost))assert(LI.DATA.items[k],`素材 ${k}`);}return `${LI.DATA.recipes.length} recipes`;});
    test("全建築素材参照",()=>{for(const b of Object.values(LI.DATA.buildings))for(const k of Object.keys(b.cost))assert(LI.DATA.items[k],`素材 ${k}`);return `${Object.keys(LI.DATA.buildings).length} buildings`;});
    test("アトラス必須スプライト",()=>{const s=window.LI_SPRITES.sprites;for(const k of ["tile.grass.0","tile.water.0","player.down.0","enemy.slime.0","building.lighthouse.4","item.axe"])assert(s[k],k);for(const [key,item] of Object.entries(LI.DATA.items))assert(s[`item.${item.sprite||key}`],`item.${item.sprite||key}`);return `${Object.keys(s).length} sprites`;});
    test("ワールド決定性",()=>{const a=LI.Save.newState(1,"TEST-SEED"),w1=LI.World.generate(a),w2=LI.World.generate(a);assert(Array.from(w1.tiles).join()===Array.from(w2.tiles).join(),"tile mismatch");assert(w1.resources.map(r=>r.type+r.x+r.y).join()===w2.resources.map(r=>r.type+r.x+r.y).join(),"resource mismatch");return a.seed;});
    test("開始資源保証",()=>{const s=LI.Save.newState(1,"START"),w=LI.World.generate(s),near=w.resources.filter(r=>Math.hypot(r.x-s.player.x,r.y-s.player.y)<100),branches=near.filter(r=>r.type==="branch").length,stones=near.filter(r=>r.type==="rock").length;assert(branches>=3,`branch ${branches}`);assert(stones>=3,`stone ${stones}`);return `branch ${branches}, stone ${stones}`;});
    test("全ランドマーク",()=>{const w=LI.World.generate(LI.Save.newState(1,"LANDMARK")),ids=new Set(w.landmarks.map(l=>l.id));for(const id of ["lighthouse","forest_altar","tide_altar","rock_altar","wind_0","wind_1","wind_2","well_old"])assert(ids.has(id),id);return `${ids.size} landmarks`;});
    test("主人公ビジュアルv2",()=>{const s=window.LI_SPRITES.sprites,dirs=["down","down_right","right","up_right","up","up_left","left","down_left"];for(const d of dirs)for(let i=0;i<4;i++)assert(s[`player.${d}.${i}`],`${d}.${i}`);for(const outfit of ["grove","tide","starlight","keeper"])for(const d of dirs)for(let i=0;i<4;i++)assert(s[`player.${outfit}.${d}.${i}`],`${outfit}.${d}.${i}`);assert(s["player.down.0"].w>=20&&s["player.down.0"].h>=34,"hero too small");return `${s["player.down.0"].w}x${s["player.down.0"].h} / 160 frames / 5 outfits`;});
    test("開始安全地帯",()=>{const s=LI.Save.newState(1,"SAFE-START"),w=LI.World.generate(s),nearest=Math.min(...w.enemies.map(e=>Math.hypot(e.x-LI.World.SANCTUARY.x,e.y-LI.World.SANCTUARY.y)));assert(nearest>=LI.World.SANCTUARY.r+32,`enemy distance ${nearest}`);assert(s.progress.enemyGraceUntil>=120,"grace");return `nearest ${Math.round(nearest)}px / grace 120s`;});
    test("収集物の到達可能性",()=>{const s=LI.Save.newState(1,"RELICS"),w=LI.World.generate(s),relics=w.landmarks.filter(l=>l.type==="relic");assert(relics.length===8,"relic count");for(const l of relics){const tile=LI.World.tileAt(w,l.x,l.y);assert(tile!==LI.World.TILE_ID.sea&&tile!==LI.World.TILE_ID.shallow,`${l.id} blocked`);}return `${relics.length} relics`;});
    test("セーブ検証と移行",()=>{const s=LI.Save.newState(2,"SAVE"),payload=JSON.stringify(s),raw=JSON.stringify({schemaVersion:1,checksum:LI.Save.hash(payload),payload}),out=LI.Save.unpack(raw);assert(out.seed===s.seed&&out.player.x===s.player.x,"roundtrip");return "checksum OK";});
    test("旧セーブP7移行",()=>{const old=LI.Save.newState(1,"OLD");old.schemaVersion=1;delete old.progress.relics;delete old.progress.commissions;delete old.progress.upgrades;delete old.progress.masteryLevels;delete old.progress.outfit;delete old.stats.distance;const payload=JSON.stringify(old),raw=JSON.stringify({schemaVersion:1,checksum:LI.Save.hash(payload),payload}),out=LI.Save.unpack(raw);assert(out.schemaVersion===2,"version");assert(out.progress.relics.length===8&&out.progress.outfit==="island","progress defaults");assert(out.stats.distance===0,"stats defaults");return "v1 → v2";});
    test("破損セーブ拒否",()=>{let rejected=false;try{LI.Save.unpack('{"schemaVersion":1,"checksum":"bad","payload":"{}"}');}catch(_){rejected=true;}assert(rejected,"accepted bad checksum");});
    test("夜間明度方針",()=>{const night=parseInt("6c",16),ink=parseInt("27",16);assert(night>ink*2,"night palette too dark");return "#6c73a8";});
    test("P7セーブ構造",()=>{const s=LI.Save.newState(1,"P7");assert(s.progress.relics.length===8,"relics");assert(Array.isArray(s.progress.commissions),"commissions");assert(s.progress.upgrades&&s.progress.masteryLevels,"progress");assert("distance" in s.stats,"stats");return `schema ${s.schemaVersion}`;});
    test("スマホ操作分離",()=>{for(const id of ["touchAction","touchTool","touchDodge","touchSelected","safeBadge"])assert(document.getElementById(id),id);assert(document.querySelectorAll(".touch-actions button").length===3,"three actions");return "context / item / dodge";});
    test("完成目標構造",()=>{assert(LI.DATA.objectives.length>=10,"objectives");assert(LI.DATA.achievements.length>=30,"achievements");assert(LI.DATA.fish.length===10,"fish");assert(LI.DATA.recipes.length>=25,"recipes");assert(Object.keys(LI.DATA.buildings).length>=27,"buildings");assert(LI.DATA.mastery.length===6,"mastery");assert(LI.DATA.upgrades.length===12,"upgrades");assert(LI.DATA.commissions.length>=8,"commissions");return `${LI.DATA.achievements.length} achievements / ${LI.DATA.upgrades.length} skills`;});
    const passed=results.filter(r=>r.ok).length,report={passed,total:results.length,ok:passed===results.length,results};console.table(results);console.info(`Lumina Isle self-test ${passed}/${results.length}`);return report;
  }
  LI.selfTest={run};
  function demo(){
    const s=LI.Save.newState(1,"SUN-DEMO");s.progress.tutorialDone=!new URLSearchParams(location.search).has("tutorial");s.clock=250;s.weather="glow";s.progress.lighthouseSeen=true;s.progress.lighthouseStage=1;s.inventory={branch:18,wood:28,stone:24,fiber:15,berry:7,seed:5,axe:1,pickaxe:1,spear:1,rod:1,hammer:1,watering_can:1};s.hotbar=["axe","pickaxe","spear","rod","berry","seed","watering_can","hammer"];
    s.buildings=[{id:"demo-fire",type:"campfire",x:34,y:51,w:1,h:1},{id:"demo-work",type:"workbench",x:38,y:50,w:2,h:1},{id:"demo-plot1",type:"plot",x:40,y:48,w:1,h:1,crop:"sunroot",stage:2,watered:true},{id:"demo-plot2",type:"plot",x:41,y:48,w:1,h:1,crop:"sunroot",stage:3,watered:false},{id:"demo-lamp",type:"lantern",x:42,y:49,w:1,h:1}];
    LI.game.startGame(s,false);
  }
  function integration(){
    const out=[];const ok=(name,value)=>{if(!value)throw new Error(name);out.push(`✓ ${name}`);};const g=LI.game;let s=LI.Save.newState(2,"INTEGRATION");s.progress.tutorialDone=true;g.startGame(s,false);s.inventory={branch:30,wood:60,stone:60,fiber:30,berry:10,seed:6,moonbean_seed:2,ore:20,copper_bar:20,crystal:20,fish:3,fish_sun:2,fish_moon:2};
    ok("安全地帯",g.isPlayerProtected()&&g.world.enemies.every(e=>Math.hypot(e.x-LI.World.SANCTUARY.x,e.y-LI.World.SANCTUARY.y)>=LI.World.SANCTUARY.r+32));
    ok("日替わり生成",s.progress.commissions.length===3);
    s.selectedHotbar=4;s.hotbar[4]="berry";const berryBefore=s.inventory.berry;document.querySelector("#touchTool").dispatchEvent(new PointerEvent("pointerdown",{bubbles:true}));ok("スマホ道具ボタン",g.state.inventory.berry===berryBefore-1);
    const branch=g.world.resources.find(r=>r.type==="branch");branch.hp=1;g.target={kind:"resource",obj:branch,d:1};document.querySelector("#touchAction").dispatchEvent(new PointerEvent("pointerdown",{bubbles:true}));ok("スマホ文脈ボタン",g.state.removedResources[branch.id]>0);
    g.craft(LI.DATA.recipes.find(r=>r.output==="axe"));ok("クラフト",g.state.inventory.axe===1);
    g.buildMode={type:"campfire",rotation:0};g.input.pointerWorldX=33.5*16;g.input.pointerWorldY=52.5*16;g.placeBuilding();s=g.state;ok("建築",s.buildings.some(b=>b.type==="campfire"));g.cancelBuild();
    const plot={id:"test-plot",type:"plot",x:34,y:52,w:1,h:1,crop:null,stage:0,watered:false};s.buildings.push(plot);s.hotbar[0]="seed";s.selectedHotbar=0;g.usePlot(plot);ok("植え付け",plot.crop==="sunroot");s.hotbar[0]="watering_can";s.inventory.watering_can=1;s.player.watering=2;g.usePlot(plot);ok("水やり",plot.watered===true);
    const plot2={id:"test-moon",type:"plot",x:35,y:52,w:1,h:1,crop:null,stage:0,watered:false};s.buildings.push(plot2);s.hotbar[0]="moonbean_seed";g.usePlot(plot2);ok("追加作物",plot2.crop==="moonbean");
    const relic=g.world.landmarks.find(l=>l.type==="relic");g.collectRelic(relic);s=g.state;ok("島の記憶",s.progress.relics[relic.index]&&s.progress.sunBadges>=2);g.state.progress.sunBadges=10;g.buyUpgrade("vitality");s=g.state;ok("技能習得",s.progress.upgrades.vitality&&s.player.maxHp===120);
    s.progress.prisms={forest:true,tide:true,rock:true};s.progress.lighthouseStage=2;g.advanceLighthouse();s=g.state;ok("プリズム設置",s.progress.lighthouseStage===3);g.advanceLighthouse();s=g.state;ok("灯台完成",s.progress.lighthouseStage===4);
    const saved=LI.Save.save(2,s),loaded=LI.Save.load(2);ok("セーブ往復",saved.ok&&loaded.state?.progress.lighthouseStage===4);
    const html=`<div class="details-card" style="font-family:monospace;line-height:1.8">${out.join("<br>")}</div>`;g.dom.ending.classList.add("is-hidden");g.endingPlaying=false;g.openCustom(`統合テスト ${out.length}/${out.length}`,"ALL PASSED",html);
  }
  function longrun(){const out=[],ok=(name,v)=>{if(!v)throw new Error(name);out.push(`✓ ${name}`);},g=LI.game,s=LI.Save.newState(3,"LONG-RUN");s.progress.tutorialDone=true;g.startGame(s,false);for(let i=0;i<180;i++)g.updateTime(10);ok("30分相当進行",g.state.day>=3);ok("生存値有限",[g.state.player.hp,g.state.player.food,g.state.player.water,g.state.player.stamina,g.state.clock].every(Number.isFinite));ok("日替わり更新",g.state.progress.commissionsDay===g.state.day&&g.state.progress.commissions.length===3);ok("上限内",g.particles.length<=250&&g.world.enemies.length<=24&&g.state.buildings.length<=400);ok("例外なし",!g.debug.lastError);g.openCustom(`長時間テスト ${out.length}/${out.length}`,"ALL PASSED",`<div class="details-card" style="font-family:monospace;line-height:1.8">${out.join("<br>")}</div>`);}
  const params=new URLSearchParams(location.search);
  if(params.has("selftest"))window.addEventListener("load",()=>setTimeout(()=>{const report=run(),lines=report.results.map(r=>`${r.ok?"✓":"✗"} ${r.name}: ${r.detail}`).join("<br>");LI.game?.openCustom(`自動テスト ${report.passed}/${report.total}`,report.ok?"ALL PASSED":"FAILED",`<div class="details-card" style="font-family:monospace;line-height:1.8">${lines}</div>`);},600));
  if(params.has("demo"))window.addEventListener("load",()=>setTimeout(demo,600));
  if(params.has("integration"))window.addEventListener("load",()=>setTimeout(()=>{try{integration();}catch(error){console.error(error);LI.game?.openCustom("統合テスト失敗","FAILED",`<div class="details-card">${error.message}</div>`);}},700));
  if(params.has("longrun"))window.addEventListener("load",()=>setTimeout(()=>{try{longrun();}catch(error){console.error(error);LI.game?.openCustom("長時間テスト失敗","FAILED",`<div class="details-card">${error.message}</div>`);}},700));
})();
